### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by Githubnoob1994** [Hyddwn/HyddwnLauncher#19]
When I try to log on the launcher it says Incorrect Username or Password and I receive an email with a Nexon verification Code Why is it doing that why can't I log on my account??

**Comment by Seeker1437** [comment]
Nexon is now verifying devices when you sign in and Hyddwn Launcher sends one that is not quite like the nexon launcher so it required the device verification but Hyddwn Launcher does not have integrated support for the device verification process.

This will change.

**Comment by Githubnoob1994** [comment]
Meaning I won't be able to log on mabi until this is fixed?...

**Comment by Seeker1437** [comment]
Not with Hyddwn Launcher

**Comment by Githubnoob1994** [comment]
Any chance this will be updated once the problem is fixed?

**Comment by Seeker1437** [comment]
Yes
