### ISSUE TITLE
Unable to open more than 1 instances for Mabinogi

### ISSUE THREAD

**Issue by mannnohmannn** [Hyddwn/HyddwnLauncher#21]
Can anyone please tell me about how I should be using this?

**Comment by Seeker1437** [comment]
Hyddwn Launcher does not add the multi-client mod to Mabinogi it simply launches the game. You will need to mod the game in order to have multi-client,

Once you have a multi-client mod installed, you can use this launcher to run more than one instance of Mabinogi.

**Comment by mannnohmannn** [comment]
Would kindly tell me about how I should get the mod/make it?
I am sorry for the trouble.

**Comment by mannnohmannn** [comment]
> Hyddwn Launcher does not add the multi-client mod to Mabinogi it simply launches the game. You will need to mod the game in order to have multi-client,
> 
> Once you have a multi-client mod installed, you can use this launcher to run more than one instance of Mabinogi.

Would you kindly tell me how I should get it?
I am sorry for the trouble.

**Comment by Seeker1437** [comment]
You’d need to get one from another source. There are a couple available. Your best bet is to look into Abyss or Kanan.

There are also mod kits that include one or the other such as Mabinogi Frontend or UOTiara.

You will need to google for these, I will not link to them.

**Comment by Seeker1437** [comment]
Closing as this issue is not directly related to the launcher.
