### ISSUE TITLE
Another Mabinogi Client is Already Running

### ISSUE THREAD

**Issue by Nexusz-eng** [Hyddwn/HyddwnLauncher#28]
![Screenshot (95)](https://user-images.githubusercontent.com/52681663/60848785-06b29f00-a1b6-11e9-9412-d7625b576f2e.png)
I'm no tech wizard, i know nothing about programming or coding or anything I barely know how to use the launcher. It has been giving me this issue and idk what exactly to do.

**Comment by Seeker1437** [comment]
Mabinogi is detecting there is another running instance of Mabinogi.

If you are trying to multiclient, you will need a mod that enables multiclient. The launcher does not do this for you.

If you are not trying to multiclient, you have another instance of Mabinogi running. You can open the task manager and close the running instance of `Client.exe`.

**Comment by Seeker1437** [comment]
Closing as this is not directly related to the launcher.
