### ISSUE TITLE
Morrighan compability

### ISSUE THREAD

**Issue by Arceni** [Hyddwn/HyddwnLauncher#29]
Can you make a fork compatible with morrighan?

**Comment by Seeker1437** [comment]
I don't mind.

**Comment by Arceni** [comment]
Also today parch broke custom launch atributes so is it possible to make it configurable without recompile?(which is not possible as i don't have new sources)

**Comment by Arceni** [comment]
V 0.11.18.0 launcher  started to autofix Client.exe at the launcher start. It breaks morri client.exe replacement.

**Comment by Seeker1437** [comment]
It is not necessary to use the Nexon Launcher compatibility with Morrighan.

You can set the client profile to start Morrighan.exe directly and it will launch the game successfully.

I will still look into fixing the compatibility with the Nexon Launcher compatibility because that is still useful.

**Comment by Arceni** [comment]
At previous version to make it compatible with morrighan i modified launch attributes "arguments" in "LaunchCustom" by adding "-NXAL" key and that worked. But now there is no up to time sources, so i can't modify it.

**Comment by Seeker1437** [comment]
Okay I am working on it.

**Comment by Arceni** [comment]
Everything works fine if i set Morrighan.exe as executable in profile. I feel myself realy stupid. Though custom launch keys will probably be good when nexon will broke everything again.

**Comment by Seeker1437** [comment]
You can not use https://github.com/Hyddwn/HyddwnLauncher/releases/tag/v0.11.18-beta.24

for custom arguments
