### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by Arceni** [Hyddwn/HyddwnLauncher#32]
Looks like Nexon broke login again already. After client start it shows login/password window so i suppose something going wrong.

**Comment by Galeronis** [comment]
I'm getting the same issue here.  Was wondering what was going on.

**Comment by MelanieTanaka** [comment]
Yeah same here for me.

**Comment by Nexusz-eng** [comment]
Me too

**Comment by Seeker1437** [comment]
A fix is available on my discord, once I get home, I can get it up on here.

**Comment by Arceni** [comment]
Can i get discord link then?

**Comment by shaggyze** [comment]
https://discord.gg/Waf2Cxn

**Comment by Arceni** [comment]
Beta 26 don't work for me. It crashing with 
Exception Details: System.NullReferenceException: An object reference does not indicate an object instance.
   in HyddwnLauncher.MainWindow. <LaunchOfficial> d__146.MoveNext ()

**Comment by Arceni** [comment]
And suddenly it works now.

**Comment by Seeker1437** [comment]
In the future can you post an error like this in it's own issue and include the entire error?

Are you still having issues with the latest beta?
