### ISSUE TITLE
How to use this Launcher?

### ISSUE THREAD

**Issue by chamchichi** [Hyddwn/HyddwnLauncher#43]
I download this link : https://github.com/Hyddwn/HyddwnLauncher/releases/tag/v2.0.0
But I can't find the executable in this file
I'm sorry for being callow :(

**Comment by Seeker1437** [comment]
Did you download from the link here?

https://puu.sh/FSxKA/79ccd17e78.png

**Comment by chamchichi** [comment]
The link you gave works very well. Thank you!

**Comment by Seeker1437** [comment]
I am happy I was able to help!

Thank you for using the launcher, you can come to the discord if you ever need help.

[Hyddwn - Discord](https://discord.gg/Waf2Cxn)
