### ISSUE TITLE
Cannot run more than two instances of mabinogi

### ISSUE THREAD

**Issue by YukimuraKyoko** [Hyddwn/HyddwnLauncher#9]
Whenever I try to open a 3rd mabinogi window, I get this message:

![image](https://user-images.githubusercontent.com/25997602/32346432-97158fb4-bfca-11e7-860d-70f1e484138e.png)

**Comment by Seeker1437** [comment]
Hey there, thanks for reporting your issue, can you please paste the exception here are well as your log?

Can you delete the offending file from your mabi location?

**Comment by Seeker1437** [comment]
The first attempt  to resolve issue did not go well, so this issue will remain open until I have released a fix which is coming shortly. Sorry for the long delay.

**Comment by Seeker1437** [comment]
I am closing this issue due to age,, however if you continue to experience this issue please create a new one. Thank you!
